### ISSUE TITLE
about the XML

### ISSUE THREAD

**Issue by Miffy1216** [yasinyildirim/ShotDetection#1]
Attached is one of the outputs. Why the begin frame number is same from the second shot to the last. And could you please explain the meaning of "frame_number"?

![xml](https://cloud.githubusercontent.com/assets/13345917/8717619/b7fa0962-2bcf-11e5-8d69-52a9e37b641d.png)

**Comment by yasinyildirim** [comment]
frame_number is the count of frames in video. from zero to total number of frames of video. The output   you attached is obviously wrong. Could you tell me which version of OpenCV you use? The program runs successfully on OpenCV 2.3. But there are some bugs on OpenCV 2.4. I have corrected mistakes and will push the changes soon. Sorry for the late reply.
